version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "4010:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../shimmie2:/var/www/html
    depends_on:
      - php-fpm
  php-fpm:
    image: php:8.2-fpm
    volumes:
      - ../shimmie2:/var/www/html

  nginx-subdir:
    image: nginx:alpine
    ports:
      - "4011:80"
    volumes:
      - ./nginx-subdir.conf:/etc/nginx/nginx.conf:ro
      - ../shimmie2:/var/www/html/gallery
    depends_on:
      - php-fpm-subdir
  php-fpm-subdir:
    image: php:8.2-fpm
    volumes:
      - ../shimmie2:/var/www/html/gallery

  lighttpd:
    build: lighttpd
    ports:
      - "4020:80"
    volumes:
      - ./lighttpd.conf:/etc/lighttpd.conf:ro
      - ../shimmie2:/var/www/html

  lighttpd-subdir:
    build: lighttpd
    ports:
      - "4021:80"
    volumes:
      - ./lighttpd-subdir.conf:/etc/lighttpd.conf:ro
      - ../shimmie2:/var/www/html/gallery

  varnish:
    image: varnish:latest
    ports:
      - "4030:80"
    volumes:
      - ./varnish.vcl:/etc/varnish/default.vcl:ro
    depends_on:
      - nginx

  apache:
    build: apache
    ports:
      - "4040:80"
    volumes:
      - ../shimmie2:/var/www/html
      - ./apache.vhost:/etc/apache2/sites-enabled/000-default.conf

  apache-subdir:
    build: apache
    ports:
      - "4041:80"
    volumes:
      - ../shimmie2:/var/www/html/gallery
      - ./apache.vhost:/etc/apache2/sites-enabled/000-default.conf
