server {
    listen 80;
    root /var/www/html;
    server_name _;

    client_max_body_size 11M;

    location /oauth2/ {
        proxy_pass http://oauth2-proxy:4180;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Auth-Request-Redirect $scheme://$http_host$request_uri;
    }

    location = /oauth2/auth {
        proxy_pass http://oauth2-proxy:4180/oauth2/auth;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header Host $host;
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
    }

    location ~ "^.*\.(css|js|map|gif|png|jpg|jpeg|ico)$" {
        try_files $uri /;
        expires 1d;
    }

    location / {
        auth_request /oauth2/auth;
        error_page 401 = @oauth2_signin;

        auth_request_set $oauth_user $upstream_http_x_auth_request_user;
        auth_request_set $oauth_email $upstream_http_x_auth_request_email;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_param HTTP_X_FORWARDED_USER $oauth_user;
        fastcgi_param HTTP_X_FORWARDED_EMAIL $oauth_email;
        fastcgi_pass php-fpm:9000;
    }

    location @oauth2_signin {
        return 302 $scheme://$http_host/oauth2/start?rd=$request_uri;
    }
}
